with 

source_1 as (
    select * from {{ source('sql_erp_prod_dbo', 'petshop_purchase_header_437dbf0e_84ff_417a_965d_ed2bb9650972') }}
),

source_2 as (
    select * from {{ source('sql_erp_prod_dbo', 'petshop_purchase_header_c91094c2_db03_49d2_8cb9_95c179ecbf9d') }}
),

renamed_source_1 as (
    select
        document_type,
        no_,
        status,
        ic_direction,
        ic_status,
        job_queue_status,
        last_receiving_no_,
        _fivetran_deleted,
        _fivetran_synced,
        _systemid,
        applies_to_doc__no_,
        applies_to_doc__type,
        applies_to_id,
        area,
        assigned_user_id,
        bal__account_no_,
        bal__account_type,
        buy_from_address,
        buy_from_address_2,
        buy_from_city,
        buy_from_contact,
        buy_from_contact_no_,
        buy_from_country_region_code,
        buy_from_county,
        buy_from_ic_partner_code,
        buy_from_post_code,
        buy_from_vendor_name,
        buy_from_vendor_name_2,
        buy_from_vendor_no_,
        campaign_no_,
        compress_prepayment,
        correction,
        creditor_no_,
        currency_code,
        currency_factor,
        dimension_set_id,
        doc__no__occurrence,
        document_date,
        due_date,
        entry_point,
        expected_receipt_date,
        gen__bus__posting_group,
        id,
        inbound_whse__handling_time,
        incoming_document_entry_no_,
        invoice,
        invoice_disc__code,
        invoice_discount_calculation,
        invoice_discount_value,
        job_queue_entry_id,
        language_code,
        last_posting_no_,
        last_prepayment_no_,
        last_prepmt__cr__memo_no_,
        last_return_shipment_no_,
        lead_time_calculation,
        location_code,
        no__printed,
        no__series,
        on_hold,
        order_address_code,
        order_class,
        order_date,
        pay_to_address,
        pay_to_address_2,
        pay_to_city,
        pay_to_contact,
        pay_to_contact_no_,
        pay_to_country_region_code,
        pay_to_county,
        pay_to_ic_partner_code,
        pay_to_name,
        pay_to_name_2,
        pay_to_post_code,
        pay_to_vendor_no_,
        payment_discount__,
        payment_method_code,
        payment_reference,
        payment_terms_code,
        pmt__discount_date,
        posting_date,
        posting_description,
        posting_from_whse__ref_,
        posting_no_,
        posting_no__series,
        prepayment__,
        prepayment_due_date,
        prepayment_no_,
        prepayment_no__series,
        prepmt__cr__memo_no_,
        prepmt__cr__memo_no__series,
        prepmt__payment_discount__,
        prepmt__payment_terms_code,
        prepmt__pmt__discount_date,
        prepmt__posting_description,
        price_calculation_method,
        prices_including_vat,
        print_posted_documents,
        promised_receipt_date,
        purchaser_code,
        quote_no_,
        reason_code,
        receive,
        receiving_no_,
        receiving_no__series,
        requested_receipt_date,
        responsibility_center,
        return_shipment_no_,
        return_shipment_no__series,
        sell_to_customer_no_,
        send_ic_document,
        ship,
        ship_to_address,
        ship_to_address_2,
        ship_to_city,
        ship_to_code,
        ship_to_contact,
        ship_to_country_region_code,
        ship_to_county,
        ship_to_name,
        ship_to_name_2,
        ship_to_post_code,
        shipment_method_code,
        shortcut_dimension_1_code,
        shortcut_dimension_2_code,
        tax_area_code,
        tax_liable,
        timestamp,
        transaction_specification,
        transaction_type,
        transport_method,
        vat_base_discount__,
        vat_bus__posting_group,
        vat_country_region_code,
        vat_registration_no_,
        vendor_authorization_no_,
        vendor_cr__memo_no_,
        vendor_invoice_no_,
        vendor_order_no_,
        vendor_posting_group,
        vendor_shipment_no_,
        your_reference
    from source_1
),

renamed_source_2 as (
    select
        document_type,
        no_,
        quality_status,
        _fivetran_deleted,
        _fivetran_synced,
        completely_qc_done,
        created_by_user,
        drop_ship_order,
        expense_amount,
        expense_template_code,
        operation_types,
        order_no_,
        purchase_type,
        qc_started,
        short_close,
        timestamp,
        isslim4sync,
        slimstock_document_no
    from source_2
),

joined as (
    select
        -- From source 1 (main table)
        --s1.document_type,
        case 
            when s1.document_type = 0 then 'Quote'         --PQ/24/10003
            when s1.document_type = 1 then 'Order'         --TPS/2025/002120
            when s1.document_type = 2 then 'Invoice'       --PI/11142
            when s1.document_type = 3 then 'Credit Memo'   --PCM/0563
            when s1.document_type = 4 then 'Blanket Order' -- not used
            when s1.document_type = 5 then 'Return Order'  --PR/2021/00001
            else 'cheack my logic'
        end as document_type,

        s1.no_,
        --s1.status,

        case 
            when s1.status = 0 then 'Open'
            when s1.status = 1 then 'Released'
            when s1.status = 2 then 'Pending Approval'
            else 'cheack'
        end as status,

        s1.ic_direction,
        s1.ic_status,
        s1.job_queue_status,
        s1.last_receiving_no_,
        s1._fivetran_deleted,
        s1._fivetran_synced,
        s1._systemid,
        s1.applies_to_doc__no_,
        s1.applies_to_doc__type,
        s1.applies_to_id,
        s1.area,
        s1.assigned_user_id,
        s1.bal__account_no_,
        s1.bal__account_type,
        s1.buy_from_address,
        s1.buy_from_address_2,
        s1.buy_from_city,
        s1.buy_from_contact,
        s1.buy_from_contact_no_,
        s1.buy_from_country_region_code,
        s1.buy_from_county,
        s1.buy_from_ic_partner_code,
        s1.buy_from_post_code,
        s1.buy_from_vendor_name,
        s1.buy_from_vendor_name_2,
        s1.buy_from_vendor_no_,
        s1.campaign_no_,
        s1.compress_prepayment,
        s1.correction,
        s1.creditor_no_,
        s1.currency_code,
        s1.currency_factor,
        s1.dimension_set_id,
        s1.doc__no__occurrence,
        s1.document_date,
        s1.due_date,
        s1.entry_point,
        s1.expected_receipt_date,
        s1.gen__bus__posting_group,
        s1.id,
        s1.inbound_whse__handling_time,
        s1.incoming_document_entry_no_,
        s1.invoice,
        s1.invoice_disc__code,
        s1.invoice_discount_calculation,
        s1.invoice_discount_value,
        s1.job_queue_entry_id,
        s1.language_code,
        s1.last_posting_no_,
        s1.last_prepayment_no_,
        s1.last_prepmt__cr__memo_no_,
        s1.last_return_shipment_no_,
        s1.lead_time_calculation,
        s1.location_code,
        s1.no__printed,
        s1.no__series,
        s1.on_hold,
        s1.order_address_code,
        s1.order_class,
        s1.order_date,
        s1.pay_to_address,
        s1.pay_to_address_2,
        s1.pay_to_city,
        s1.pay_to_contact,
        s1.pay_to_contact_no_,
        s1.pay_to_country_region_code,
        s1.pay_to_county,
        s1.pay_to_ic_partner_code,
        s1.pay_to_name,
        s1.pay_to_name_2,
        s1.pay_to_post_code,
        s1.pay_to_vendor_no_,
        s1.payment_discount__,
        s1.payment_method_code,
        s1.payment_reference,
        s1.payment_terms_code,
        s1.pmt__discount_date,
        s1.posting_date,
        s1.posting_description,
        s1.posting_from_whse__ref_,
        s1.posting_no_,
        s1.posting_no__series,
        s1.prepayment__,
        s1.prepayment_due_date,
        s1.prepayment_no_,
        s1.prepayment_no__series,
        s1.prepmt__cr__memo_no_,
        s1.prepmt__cr__memo_no__series,
        s1.prepmt__payment_discount__,
        s1.prepmt__payment_terms_code,
        s1.prepmt__pmt__discount_date,
        s1.prepmt__posting_description,
        s1.price_calculation_method,
        s1.prices_including_vat,
        s1.print_posted_documents,
        s1.promised_receipt_date,
        s1.purchaser_code,
        s1.quote_no_,
        s1.reason_code,
        s1.receive,
        s1.receiving_no_,
        s1.receiving_no__series,
        s1.requested_receipt_date,
        s1.responsibility_center,
        s1.return_shipment_no_,
        s1.return_shipment_no__series,
        s1.sell_to_customer_no_,
        s1.send_ic_document,
        s1.ship,
        s1.ship_to_address,
        s1.ship_to_address_2,
        s1.ship_to_city,
        s1.ship_to_code,
        s1.ship_to_contact,
        s1.ship_to_country_region_code,
        s1.ship_to_county,
        s1.ship_to_name,
        s1.ship_to_name_2,
        s1.ship_to_post_code,
        s1.shipment_method_code,
        s1.shortcut_dimension_1_code,
        s1.shortcut_dimension_2_code,
        s1.tax_area_code,
        s1.tax_liable,
        s1.timestamp,
        s1.transaction_specification,
        s1.transaction_type,
        s1.transport_method,
        s1.vat_base_discount__,
        s1.vat_bus__posting_group,
        s1.vat_country_region_code,
        s1.vat_registration_no_,
        s1.vendor_authorization_no_,
        s1.vendor_cr__memo_no_,
        s1.vendor_invoice_no_,
        s1.vendor_order_no_,
        s1.vendor_posting_group,
        s1.vendor_shipment_no_,
        s1.your_reference,
        
        -- From source 2 (additional fields)
        --s2.quality_status,

        case 
            when s2.quality_status = 0 then ''
            when s2.quality_status = 1 then 'Pass'
            else 'cheack'
        end as quality_status,

        s2.completely_qc_done,
        s2.created_by_user,
        s2.drop_ship_order,
        s2.expense_amount,
        s2.expense_template_code,
        s2.operation_types,
        s2.order_no_,
        --s2.purchase_type,

        case 
            when s2.purchase_type = 0 then 'Trade'
            when s2.purchase_type = 1 then 'Service'
            when s2.purchase_type = 2 then 'Consignment'
            when s2.purchase_type = 3 then 'Other'
            else 'cheack'
        end as purchase_type,

        s2.qc_started,
        s2.short_close,
        s2.isslim4sync,
        s2.slimstock_document_no

    from renamed_source_1 s1
    left join renamed_source_2 s2
        on s1.no_ = s2.no_
)

select * from joined


--where no_ = 'TPS/2025/001411'

