with 

source as (

    select * from {{ source('sql_erp_prod_dbo', 'petshop_purch__rcpt__line_437dbf0e_84ff_417a_965d_ed2bb9650972') }}

),

renamed as (

    select
        document_no_,
        order_no_,

        
        line_no_,
        _fivetran_deleted,
        _fivetran_synced,
        _systemid,
        allow_invoice_disc_,
        appl__to_item_entry,
        area,
        attached_to_line_no_,
        bin_code,
        blanket_order_line_no_,
        blanket_order_no_,
        budgeted_fa_no_,
        buy_from_vendor_no_,
        correction,
        cross_reference_no_,
        cross_reference_type,
        cross_reference_type_no_,
        depr__acquisition_cost,
        depr__until_fa_posting_date,
        depreciation_book_code,
        description,
        description_2,
        dimension_set_id,
        direct_unit_cost,
        duplicate_in_depreciation_book,
        entry_point,
        expected_receipt_date,
        fa_posting_date,
        fa_posting_type,
        gen__bus__posting_group,
        gen__prod__posting_group,
        gross_weight,
        ic_partner_ref__type,
        ic_partner_reference,
        inbound_whse__handling_time,
        indirect_cost__,
        insurance_no_,
        item_category_code,
        item_charge_base_amount,
        item_rcpt__entry_no_,
        job_currency_code,
        job_currency_factor,
        job_line_amount,
        job_line_amount__lcy_,
        job_line_disc__amount__lcy_,
        job_line_discount__,
        job_line_discount_amount,
        job_line_type,
        job_no_,
        job_task_no_,
        job_total_price,
        job_total_price__lcy_,
        job_unit_price,
        job_unit_price__lcy_,
        lead_time_calculation,
        line_discount__,
        location_code,
        maintenance_code,
        net_weight,
        no_,
        nonstock,
        operation_no_,
        order_date,
        order_line_no_,
        
        over_receipt_code,
        over_receipt_code_2,
        over_receipt_quantity,
        overhead_rate,
        pay_to_vendor_no_,
        planned_receipt_date,
        posting_date,
        posting_group,
        prod__order_line_no_,
        prod__order_no_,
        product_group_code,
        promised_receipt_date,
        purchasing_code,
        qty__invoiced__base_,
        qty__per_unit_of_measure,
        qty__rcd__not_invoiced,
        quantity,
        quantity__base_,
        quantity_invoiced,
        requested_receipt_date,
        responsibility_center,
        return_reason_code,
        routing_no_,
        routing_reference_no_,
        sales_order_line_no_,
        sales_order_no_,
        salvage_value,
        shortcut_dimension_1_code,
        shortcut_dimension_2_code,
        special_order_sales_line_no_,
        special_order_sales_no_,
        tax_area_code,
        tax_group_code,
        tax_liable,
        timestamp,
        transaction_specification,
        transaction_type,
        transport_method,
        type,
        unit_cost,
        unit_cost__lcy_,
        unit_of_measure,
        unit_of_measure__cross_ref__,
        unit_of_measure_code,
        unit_price__lcy_,
        unit_volume,
        units_per_parcel,
        use_duplication_list,
        use_tax,
        variant_code,
        vat__,
        vat_base_amount,
        vat_bus__posting_group,
        vat_calculation_type,
        vat_prod__posting_group,
        vendor_item_no_,
        work_center_no_

    from source

)

select * from renamed

--where order_no_ = 'TPS/2024/001236'

